version: 2
enable-beta-ecosystems: true
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: "pub"
  directory: "/mobile/"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
- package-ecosystem: gradle
  directory: "/mobile/android/app"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/mobile/android"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/backend"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/backend/api"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/backend/article-parser"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/backend/common"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/backend/crawlers/common"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/backend/crawlers/cli"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/backend/crawlers/discoverdev.io"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/backend/crawlers/engineeringblogs.xyz"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/backend/crawlers/rm3l.org"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/backend/persistence"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/backend/screenshot"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
- package-ecosystem: docker
  directory: "/backend"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
