version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/backend"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "docker"
    directory: "/backend"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

